apiVersion: v1
kind: Service
metadata:
  name: base-dev-challenge
  labels:
    project: base
    environment: dev
    app: challenge
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    project: base
    environment: dev
    app: challenge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-dev-challenge
  labels:
    project: base
    environment: dev
    app: challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      project: base
      environment: dev
      app: challenge
  template:
    metadata:
      labels:
        project: base
        environment: dev
        app: challenge
    spec:
      containers:
        - name: base-dev-challenge
          image: base-dev-challenge:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: base-dev-challenge-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  defaultBackend:
    service:
      name: base-dev-challenge
      port:
        number: 80
  rules:
  - host: challenge.base.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: base-dev-challenge
            port:
              number: 80
